export const countries = [
  // UEFA
  { name: 'Albania', flag: 'https://flagcdn.com/w320/al.png', code: 'ALB' },
  { name: 'Armenia', flag: 'https://flagcdn.com/w320/am.png', code: 'ARM' },
  { name: 'Austria', flag: 'https://flagcdn.com/w320/at.png', code: 'AUT' },
  { name: 'Belgium', flag: 'https://flagcdn.com/w320/be.png', code: 'BEL' },
  { name: 'Bosnia and Herzegovina', flag: 'https://flagcdn.com/w320/ba.png', code: 'BIH' },
  { name: 'Bulgaria', flag: 'https://flagcdn.com/w320/bg.png', code: 'BUL' },
  { name: 'Croatia', flag: 'https://flagcdn.com/w320/hr.png', code: 'CRO' },
  { name: 'Cyprus', flag: 'https://flagcdn.com/w320/cy.png', code: 'CYP' },
  { name: 'Czech Republic', flag: 'https://flagcdn.com/w320/cz.png', code: 'CZE' },
  { name: 'Denmark', flag: 'https://flagcdn.com/w320/dk.png', code: 'DEN' },
  { name: 'England', flag: 'https://flagcdn.com/w320/gb-eng.png', code: 'ENG' },
  { name: 'Estonia', flag: 'https://flagcdn.com/w320/ee.png', code: 'EST' },
  { name: 'Finland', flag: 'https://flagcdn.com/w320/fi.png', code: 'FIN' },
  { name: 'France', flag: 'https://flagcdn.com/w320/fr.png', code: 'FRA' },
  { name: 'Georgia', flag: 'https://flagcdn.com/w320/ge.png', code: 'GEO' },
  { name: 'Germany', flag: 'https://flagcdn.com/w320/de.png', code: 'GER' },
  { name: 'Greece', flag: 'https://flagcdn.com/w320/gr.png', code: 'GRE' },
  { name: 'Hungary', flag: 'https://flagcdn.com/w320/hu.png', code: 'HUN' },
  { name: 'Iceland', flag: 'https://flagcdn.com/w320/is.png', code: 'ISL' },
  { name: 'Ireland', flag: 'https://flagcdn.com/w320/ie.png', code: 'IRL' },
  { name: 'Israel', flag: 'https://flagcdn.com/w320/il.png', code: 'ISR' },
  { name: 'Italy', flag: 'https://flagcdn.com/w320/it.png', code: 'ITA' },
  { name: 'Kosovo', flag: 'https://flagcdn.com/w320/xk.png', code: 'KVX' },
  { name: 'Lithuania', flag: 'https://flagcdn.com/w320/lt.png', code: 'LTU' },
  { name: 'Luxembourg', flag: 'https://flagcdn.com/w320/lu.png', code: 'LUX' },
  { name: 'Montenegro', flag: 'https://flagcdn.com/w320/me.png', code: 'MNE' },
  { name: 'Netherlands', flag: 'https://flagcdn.com/w320/nl.png', code: 'NED' },
  { name: 'North Macedonia', flag: 'https://flagcdn.com/w320/mk.png', code: 'MKD' },
  { name: 'Northern Ireland', flag: 'https://flagcdn.com/w320/gb-nir.png', code: 'NIR' },
  { name: 'Norway', flag: 'https://flagcdn.com/w320/no.png', code: 'NOR' },
  { name: 'Poland', flag: 'https://flagcdn.com/w320/pl.png', code: 'POL' },
  { name: 'Portugal', flag: 'https://flagcdn.com/w320/pt.png', code: 'POR' },
  { name: 'Romania', flag: 'https://flagcdn.com/w320/ro.png', code: 'ROU' },
  { name: 'Russia', flag: 'https://flagcdn.com/w320/ru.png', code: 'RUS' },
  { name: 'Scotland', flag: 'https://flagcdn.com/w320/gb-sct.png', code: 'SCO' },
  { name: 'Serbia', flag: 'https://flagcdn.com/w320/rs.png', code: 'SRB' },
  { name: 'Slovakia', flag: 'https://flagcdn.com/w320/sk.png', code: 'SVK' },
  { name: 'Slovenia', flag: 'https://flagcdn.com/w320/si.png', code: 'SVN' },
  { name: 'Spain', flag: 'https://flagcdn.com/w320/es.png', code: 'ESP' },
  { name: 'Sweden', flag: 'https://flagcdn.com/w320/se.png', code: 'SWE' },
  { name: 'Switzerland', flag: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Civil_Ensign_of_Switzerland_%28Pantone%29.svg/1920px-Civil_Ensign_of_Switzerland_%28Pantone%29.svg.png?utm_source=en.wikipedia.org&utm_campaign=imageinfo&utm_content=thumbnail', code: 'SUI' },
  { name: 'Turkey', flag: 'https://flagcdn.com/w320/tr.png', code: 'TUR' },
  { name: 'Ukraine', flag: 'https://flagcdn.com/w320/ua.png', code: 'UKR' },
  { name: 'Wales', flag: 'https://flagcdn.com/w320/gb-wls.png', code: 'WAL' },
  // CONMEBOL
  { name: 'Argentina', flag: 'https://flagcdn.com/w320/ar.png', code: 'ARG' },
  { name: 'Brazil', flag: 'https://flagcdn.com/w320/br.png', code: 'BRA' },
  { name: 'Chile', flag: 'https://flagcdn.com/w320/cl.png', code: 'CHI' },
  { name: 'Colombia', flag: 'https://flagcdn.com/w320/co.png', code: 'COL' },
  { name: 'Ecuador', flag: 'https://flagcdn.com/w320/ec.png', code: 'ECU' },
  { name: 'Paraguay', flag: 'https://flagcdn.com/w320/py.png', code: 'PAR' },
  { name: 'Peru', flag: 'https://flagcdn.com/w320/pe.png', code: 'PER' },
  { name: 'Uruguay', flag: 'https://flagcdn.com/w320/uy.png', code: 'URU' },
  { name: 'Venezuela', flag: 'https://flagcdn.com/w320/ve.png', code: 'VEN' },
  // CONCACAF
  { name: 'Canada', flag: 'https://flagcdn.com/w320/ca.png', code: 'CAN' },
  { name: 'Costa Rica', flag: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Flag_of_Costa_Rica.svg/1920px-Flag_of_Costa_Rica.svg.png?utm_source=en.wikipedia.org&utm_campaign=imageinfo&utm_content=thumbnail', code: 'CRC' },
  { name: 'Dominican Republic', flag: 'https://flagcdn.com/w320/do.png', code: 'DOM' },
  { name: 'French Guiana', flag: 'https://flagcdn.com/w320/gf.png', code: 'GUF' },
  { name: 'Guadeloupe', flag: 'https://flagcdn.com/w320/gp.png', code: 'GLP' },
  { name: 'Haiti', flag: 'https://flagcdn.com/w320/ht.png', code: 'HAI' },
  { name: 'Honduras', flag: 'https://flagcdn.com/w320/hn.png', code: 'HON' },
  { name: 'Jamaica', flag: 'https://flagcdn.com/w320/jm.png', code: 'JAM' },
  { name: 'Martinique', flag: 'https://flagcdn.com/w320/mq.png', code: 'MTQ' },
  { name: 'Mexico', flag: 'https://flagcdn.com/w320/mx.png', code: 'MEX' },
  { name: 'Suriname', flag: 'https://flagcdn.com/w320/sr.png', code: 'SUR' },
  { name: 'United States', flag: 'https://flagcdn.com/w320/us.png', code: 'USA' },
  // CAF
  { name: 'Algeria', flag: 'https://flagcdn.com/w320/dz.png', code: 'ALG' },
  { name: 'Angola', flag: 'https://flagcdn.com/w320/ao.png', code: 'ANG' },
  { name: 'Benin', flag: 'https://flagcdn.com/w320/bj.png', code: 'BEN' },
  { name: 'Burkina Faso', flag: 'https://flagcdn.com/w320/bf.png', code: 'BFA' },
  { name: 'Cameroon', flag: 'https://flagcdn.com/w320/cm.png', code: 'CMR' },
  { name: 'Central African Republic', flag: 'https://flagcdn.com/w320/cf.png', code: 'CAF' },
  { name: 'Comoros', flag: 'https://flagcdn.com/w320/km.png', code: 'COM' },
  { name: 'Congo', flag: 'https://flagcdn.com/w320/cg.png', code: 'COG' },
  { name: 'DR Congo', flag: 'https://flagcdn.com/w320/cd.png', code: 'COD' },
  { name: 'Egypt', flag: 'https://flagcdn.com/w320/eg.png', code: 'EGY' },
  { name: 'Gabon', flag: 'https://flagcdn.com/w320/ga.png', code: 'GAB' },
  { name: 'Gambia', flag: 'https://flagcdn.com/w320/gm.png', code: 'GAM' },
  { name: 'Ghana', flag: 'https://flagcdn.com/w320/gh.png', code: 'GHA' },
  { name: 'Guinea', flag: 'https://flagcdn.com/w320/gn.png', code: 'GUI' },
  { name: 'Guinea-Bissau', flag: 'https://flagcdn.com/w320/gw.png', code: 'GNB' },
  { name: 'Ivory Coast', flag: 'https://flagcdn.com/w320/ci.png', code: 'CIV' },
  { name: 'Mali', flag: 'https://flagcdn.com/w320/ml.png', code: 'MLI' },
  { name: 'Mauritania', flag: 'https://flagcdn.com/w320/mr.png', code: 'MRT' },
  { name: 'Mayotte', flag: 'https://flagcdn.com/w320/fr.png', code: 'MTT' },
  { name: 'Morocco', flag: 'https://flagcdn.com/w320/ma.png', code: 'MAR' },
  { name: 'Nigeria', flag: 'https://flagcdn.com/w320/ng.png', code: 'NGA' },
  { name: 'Senegal', flag: 'https://flagcdn.com/w320/sn.png', code: 'SEN' },
  { name: 'South Africa', flag: 'https://flagcdn.com/w320/za.png', code: 'RSA' },
  { name: 'Togo', flag: 'https://flagcdn.com/w320/tg.png', code: 'TGO' },
  { name: 'Tunisia', flag: 'https://flagcdn.com/w320/tn.png', code: 'TUN' },
  { name: 'Zambia', flag: 'https://flagcdn.com/w320/zm.png', code: 'ZAM' },
  // AFC/OFC
  { name: 'Australia', flag: 'https://flagcdn.com/w320/au.png', code: 'AUS' },
  { name: 'Indonesia', flag: 'https://flagcdn.com/w320/id.png', code: 'IDN' },
  { name: 'Japan', flag: 'https://flagcdn.com/w320/jp.png', code: 'JPN' },
  { name: 'Kuwait', flag: 'https://flagcdn.com/w320/kw.png', code: 'KUW' },
  { name: 'Malaysia', flag: 'https://flagcdn.com/w320/my.png', code: 'MAS' },
  { name: 'New Zealand', flag: 'https://flagcdn.com/w320/nz.png', code: 'NZL' },
  { name: 'Philippines', flag: 'https://flagcdn.com/w320/ph.png', code: 'PHI' },
  { name: 'Saudi Arabia', flag: 'https://flagcdn.com/w320/sa.png', code: 'KSA' },
  { name: 'South Korea', flag: 'https://flagcdn.com/w320/kr.png', code: 'KOR' },
  { name: 'Thailand', flag: 'https://flagcdn.com/w320/th.png', code: 'THA' },
];