export const countries = [
  // Europa (UEFA)
  { name: 'Albania', flag: 'https://flagcdn.com/w320/al.png', code: 'ALB' },
  { name: 'Andorra', flag: 'https://flagcdn.com/w320/ad.png', code: 'AND' },
  { name: 'Armenia', flag: 'https://flagcdn.com/w320/am.png', code: 'ARM' },
  { name: 'Austria', flag: 'https://flagcdn.com/w320/at.png', code: 'AUT' },
  { name: 'Azerbaijan', flag: 'https://flagcdn.com/w320/az.png', code: 'AZE' },
  { name: 'Belarus', flag: 'https://flagcdn.com/w320/by.png', code: 'BLR' },
  { name: 'Belgium', flag: 'https://flagcdn.com/w320/be.png', code: 'BEL' },
  { name: 'Bosnia and Herzegovina', flag: 'https://flagcdn.com/w320/ba.png', code: 'BIH' },
  { name: 'Bulgaria', flag: 'https://flagcdn.com/w320/bg.png', code: 'BUL' },
  { name: 'Croatia', flag: 'https://flagcdn.com/w320/hr.png', code: 'CRO' },
  { name: 'Cyprus', flag: 'https://flagcdn.com/w320/cy.png', code: 'CYP' },
  { name: 'Czech Republic', flag: 'https://flagcdn.com/w320/cz.png', code: 'CZE' },
  { name: 'Denmark', flag: 'https://flagcdn.com/w320/dk.png', code: 'DEN' },
  { name: 'England', flag: 'https://flagcdn.com/w320/gb-eng.png', code: 'ENG' },
  { name: 'Estonia', flag: 'https://flagcdn.com/w320/ee.png', code: 'EST' },
  { name: 'Finland', flag: 'https://flagcdn.com/w320/fi.png', code: 'FIN' },
  { name: 'France', flag: 'https://flagcdn.com/w320/fr.png', code: 'FRA' },
  { name: 'Georgia', flag: 'https://flagcdn.com/w320/ge.png', code: 'GEO' },
  { name: 'Germany', flag: 'https://flagcdn.com/w320/de.png', code: 'GER' },
  { name: 'Gibraltar', flag: 'https://flagcdn.com/w320/gi.png', code: 'GIB' },
  { name: 'Greece', flag: 'https://flagcdn.com/w320/gr.png', code: 'GRE' },
  { name: 'Hungary', flag: 'https://flagcdn.com/w320/hu.png', code: 'HUN' },
  { name: 'Iceland', flag: 'https://flagcdn.com/w320/is.png', code: 'ISL' },
  { name: 'Ireland', flag: 'https://flagcdn.com/w320/ie.png', code: 'IRL' },
  { name: 'Israel', flag: 'https://flagcdn.com/w320/il.png', code: 'ISR' },
  { name: 'Italy', flag: 'https://flagcdn.com/w320/it.png', code: 'ITA' },
  { name: 'Kazakhstan', flag: 'https://flagcdn.com/w320/kz.png', code: 'KAZ' },
  { name: 'Kosovo', flag: 'https://flagcdn.com/w320/xk.png', code: 'KVX' },
  { name: 'Latvia', flag: 'https://flagcdn.com/w320/lv.png', code: 'LVA' },
  { name: 'Liechtenstein', flag: 'https://flagcdn.com/w320/li.png', code: 'LIE' },
  { name: 'Lithuania', flag: 'https://flagcdn.com/w320/lt.png', code: 'LTU' },
  { name: 'Luxembourg', flag: 'https://flagcdn.com/w320/lu.png', code: 'LUX' },
  { name: 'Malta', flag: 'https://flagcdn.com/w320/mt.png', code: 'MLT' },
  { name: 'Moldova', flag: 'https://flagcdn.com/w320/md.png', code: 'MDA' },
  { name: 'Montenegro', flag: 'https://flagcdn.com/w320/me.png', code: 'MNE' },
  { name: 'Netherlands', flag: 'https://flagcdn.com/w320/nl.png', code: 'NED' },
  { name: 'North Macedonia', flag: 'https://flagcdn.com/w320/mk.png', code: 'MKD' },
  { name: 'Northern Ireland', flag: 'https://flagcdn.com/w320/gb-nir.png', code: 'NIR' },
  { name: 'Norway', flag: 'https://flagcdn.com/w320/no.png', code: 'NOR' },
  { name: 'Poland', flag: 'https://flagcdn.com/w320/pl.png', code: 'POL' },
  { name: 'Portugal', flag: 'https://flagcdn.com/w320/pt.png', code: 'POR' },
  { name: 'Romania', flag: 'https://flagcdn.com/w320/ro.png', code: 'ROU' },
  { name: 'Russia', flag: 'https://flagcdn.com/w320/ru.png', code: 'RUS' },
  { name: 'San Marino', flag: 'https://flagcdn.com/w320/sm.png', code: 'SMR' },
  { name: 'Scotland', flag: 'https://flagcdn.com/w320/gb-sct.png', code: 'SCO' },
  { name: 'Serbia', flag: 'https://flagcdn.com/w320/rs.png', code: 'SRB' },
  { name: 'Slovakia', flag: 'https://flagcdn.com/w320/sk.png', code: 'SVK' },
  { name: 'Slovenia', flag: 'https://flagcdn.com/w320/si.png', code: 'SVN' },
  { name: 'Spain', flag: 'https://flagcdn.com/w320/es.png', code: 'ESP' },
  { name: 'Sweden', flag: 'https://flagcdn.com/w320/se.png', code: 'SWE' },
  { name: 'Switzerland', flag: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Civil_Ensign_of_Switzerland_%28Pantone%29.svg/1920px-Civil_Ensign_of_Switzerland_%28Pantone%29.svg.png?utm_source=en.wikipedia.org&utm_campaign=imageinfo&utm_content=thumbnail', code: 'SUI' },
  { name: 'Turkey', flag: 'https://flagcdn.com/w320/tr.png', code: 'TUR' },
  { name: 'Ukraine', flag: 'https://flagcdn.com/w320/ua.png', code: 'UKR' },
  { name: 'Wales', flag: 'https://flagcdn.com/w320/gb-wls.png', code: 'WAL' },
  // Sudamérica (CONMEBOL)
  { name: 'Argentina', flag: 'https://flagcdn.com/w320/ar.png', code: 'ARG' },
  { name: 'Bolivia', flag: 'https://flagcdn.com/w320/bo.png', code: 'BOL' },
  { name: 'Brazil', flag: 'https://flagcdn.com/w320/br.png', code: 'BRA' },
  { name: 'Chile', flag: 'https://flagcdn.com/w320/cl.png', code: 'CHI' },
  { name: 'Colombia', flag: 'https://flagcdn.com/w320/co.png', code: 'COL' },
  { name: 'Ecuador', flag: 'https://flagcdn.com/w320/ec.png', code: 'ECU' },
  { name: 'Paraguay', flag: 'https://flagcdn.com/w320/py.png', code: 'PAR' },
  { name: 'Peru', flag: 'https://flagcdn.com/w320/pe.png', code: 'PER' },
  { name: 'Uruguay', flag: 'https://flagcdn.com/w320/uy.png', code: 'URU' },
  { name: 'Venezuela', flag: 'https://flagcdn.com/w320/ve.png', code: 'VEN' },
  // Norte, Centroamérica y Caribe (CONCACAF)
  { name: 'Canada', flag: 'https://flagcdn.com/w320/ca.png', code: 'CAN' },
  { name: 'Costa Rica', flag: 'https://flagcdn.com/w320/cr.png', code: 'CRC' },
  { name: 'Cuba', flag: 'https://flagcdn.com/w320/cu.png', code: 'CUB' },
  { name: 'Dominican Republic', flag: 'https://flagcdn.com/w320/do.png', code: 'DOM' },
  { name: 'El Salvador', flag: 'https://flagcdn.com/w320/sv.png', code: 'SLV' },
  { name: 'Guatemala', flag: 'https://flagcdn.com/w320/gt.png', code: 'GUA' },
  { name: 'Haiti', flag: 'https://flagcdn.com/w320/ht.png', code: 'HAI' },
  { name: 'Honduras', flag: 'https://flagcdn.com/w320/hn.png', code: 'HON' },
  { name: 'Jamaica', flag: 'https://flagcdn.com/w320/jm.png', code: 'JAM' },
  { name: 'Mexico', flag: 'https://flagcdn.com/w320/mx.png', code: 'MEX' },
  { name: 'Nicaragua', flag: 'https://flagcdn.com/w320/ni.png', code: 'NCA' },
  { name: 'Panama', flag: 'https://flagcdn.com/w320/pa.png', code: 'PAN' },
  { name: 'United States', flag: 'https://flagcdn.com/w320/us.png', code: 'USA' },
  // África (CAF)
  { name: 'Algeria', flag: 'https://flagcdn.com/w320/dz.png', code: 'ALG' },
  { name: 'Cameroon', flag: 'https://flagcdn.com/w320/cm.png', code: 'CMR' },
  { name: 'Egypt', flag: 'https://flagcdn.com/w320/eg.png', code: 'EGY' },
  { name: 'Ghana', flag: 'https://flagcdn.com/w320/gh.png', code: 'GHA' },
  { name: 'Ivory Coast', flag: 'https://flagcdn.com/w320/ci.png', code: 'CIV' },
  { name: 'Morocco', flag: 'https://flagcdn.com/w320/ma.png', code: 'MAR' },
  { name: 'Nigeria', flag: 'https://flagcdn.com/w320/ng.png', code: 'NGA' },
  { name: 'Senegal', flag: 'https://flagcdn.com/w320/sn.png', code: 'SEN' },
  { name: 'South Africa', flag: 'https://flagcdn.com/w320/za.png', code: 'RSA' },
  { name: 'Tunisia', flag: 'https://flagcdn.com/w320/tn.png', code: 'TUN' },
  // Asia y Oceanía (AFC / OFC)
  { name: 'Australia', flag: 'https://flagcdn.com/w320/au.png', code: 'AUS' },
  { name: 'China', flag: 'https://flagcdn.com/w320/cn.png', code: 'CHN' },
  { name: 'Japan', flag: 'https://flagcdn.com/w320/jp.png', code: 'JPN' },
  { name: 'New Zealand', flag: 'https://flagcdn.com/w320/nz.png', code: 'NZL' },
  { name: 'Qatar', flag: 'https://flagcdn.com/w320/qa.png', code: 'QAT' },
  { name: 'Saudi Arabia', flag: 'https://flagcdn.com/w320/sa.png', code: 'KSA' },
  { name: 'South Korea', flag: 'https://flagcdn.com/w320/kr.png', code: 'KOR' }
];