export const teams = [
  // England (ENG)
  { name: 'AFC Bournemouth', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/65.png', tc: 'ENG' },
  { name: 'Arsenal FC', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/127.png', tc: 'ENG' },
  { name: 'Aston Villa FC', logo: 'https://img.a.transfermarkt.technology/wappen/homepageWappen150x150/405.png?lm=4711', tc: 'ENG' },
  { name: 'Brentford FC', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/274.png', tc: 'ENG' },
  { name: 'Brighton & Hove Albion', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/276.png', tc: 'ENG' },
  { name: 'Chelsea FC', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/373.png', tc: 'ENG' },
  { name: 'Coventry City', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/419.png', tc: 'ENG' },
  { name: 'Crystal Palace', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/429.png', tc: 'ENG' },
  { name: 'Everton FC', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/573.png', tc: 'ENG' },
  { name: 'Fulham FC', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/847.png', tc: 'ENG' },
  { name: 'Hull City AFC', logo: 'https://img.a.transfermarkt.technology/wappen/homepageWappen150x150/3008.png?lm=4711', tc: 'ENG' },
  { name: 'Ipswich Town', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1058.png', tc: 'ENG' },
  { name: 'Leeds United', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1197.png', tc: 'ENG' },
  { name: 'Liverpool FC', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1226.png', tc: 'ENG' },
  { name: 'Manchester City', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1267.png', tc: 'ENG' },
  { name: 'Manchester United', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1268.png', tc: 'ENG' },
  { name: 'Newcastle United', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1355.png', tc: 'ENG' },
  { name: 'Nottingham Forest', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1391.png', tc: 'ENG' },
  { name: 'Sunderland AFC', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1844.png', tc: 'ENG' },
  { name: 'Tottenham Hotspur', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1924.png', tc: 'ENG' },

  // France (FRA)
  { name: 'AJ Auxerre', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/75.png', tc: 'FRA' },
  { name: 'Angers SCO', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/104.png', tc: 'FRA' },
  { name: 'AS Monaco', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/136.png', tc: 'FRA' },
  { name: 'ESTAC Troyes', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/562.png', tc: 'FRA' },
  { name: 'FC Lorient', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/663.png', tc: 'FRA' },
  { name: 'Le Havre AC', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1190.png', tc: 'FRA' },
  { name: 'Le Mans FC', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1191.png', tc: 'FRA' },
  { name: 'Lille OSC', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1435.png', tc: 'FRA' },
  { name: 'OGC Nice', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1408.png', tc: 'FRA' },
  { name: 'Olympique de Marseille', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1421.png', tc: 'FRA' },
  { name: 'Olympique Lyonnais', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1420.png', tc: 'FRA' },
  { name: 'Paris FC', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1456.png', tc: 'FRA' },
  { name: 'Paris Saint-Germain', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1457.png', tc: 'FRA' },
  { name: 'RC Lens', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1539.png', tc: 'FRA' },
  { name: 'RC Strasbourg', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1540.png', tc: 'FRA' },
  { name: 'Stade Brest', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1806.png', tc: 'FRA' },
  { name: 'Stade Rennais FC', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1811.png', tc: 'FRA' },
  { name: 'Toulouse FC', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1925.png', tc: 'FRA' },

  // Germany (GER)
  { name: '1. FC Köln', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/9.png', tc: 'GER' },
  { name: '1. FC Union Berlin', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/19.png', tc: 'GER' },
  { name: '1. FSV Mainz 05', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/21.png', tc: 'GER' },
  { name: 'Bayer 04 Leverkusen', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/205.png', tc: 'GER' },
  { name: 'Borussia Dortmund', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/258.png', tc: 'GER' },
  { name: 'Borussia Mönchengladbach', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/253.png', tc: 'GER' },
  { name: 'Eintracht Frankfurt', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/530.png', tc: 'GER' },
  { name: 'FC Augsburg', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/594.png', tc: 'GER' },
  { name: 'FC Bayern Munich', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/209.png', tc: 'GER' },
  { name: 'FC Schalke 04', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/694.png', tc: 'GER' },
  { name: 'Hamburger SV', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/943.png', tc: 'GER' },
  { name: 'RB Leipzig', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/29680.png', tc: 'GER' },
  { name: 'SC Freiburg', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1639.png', tc: 'GER' },
  { name: 'SC Paderborn 07', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1651.png', tc: 'GER' },
  { name: 'SV 07 Elversberg', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/13214.png', tc: 'GER' },
  { name: 'TSG 1899 Hoffenheim', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/24.png', tc: 'GER' },
  { name: 'VfB Stuttgart', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/2076.png', tc: 'GER' },
  { name: 'Werder Bremen', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/2134.png', tc: 'GER' },

  // Italy (ITA)
  { name: 'AC Milan', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/43.png', tc: 'ITA' },
  { name: 'AC Monza', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/13760.png', tc: 'ITA' },
  { name: 'ACF Fiorentina', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/48.png', tc: 'ITA' },
  { name: 'AS Roma', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/138.png', tc: 'ITA' },
  { name: 'Atalanta BC', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/155.png', tc: 'ITA' },
  { name: 'Bologna FC 1909', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/249.png', tc: 'ITA' },
  { name: 'Cagliari Calcio', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/312.png', tc: 'ITA' },
  { name: 'Como 1907', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/17583.png', tc: 'ITA' },
  { name: 'Frosinone Calcio', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/840.png', tc: 'ITA' },
  { name: 'Genoa CFC', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/626.png', tc: 'ITA' },
  { name: 'Internazionale Milano', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1052.png', tc: 'ITA' },
  { name: 'Juventus FC', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1094.png', tc: 'ITA' },
  { name: 'Parma Calcio 1913', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1458.png', tc: 'ITA' },
  { name: 'SS Lazio', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1187.png', tc: 'ITA' },
  { name: 'SSC Napoli', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1794.png', tc: 'ITA' },
  { name: 'Torino FC', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1916.png', tc: 'ITA' },
  { name: 'Udinese Calcio', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1983.png', tc: 'ITA' },
  { name: 'US Lecce', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/2020.png', tc: 'ITA' },
  { name: 'US Sassuolo', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/13744.png', tc: 'ITA' },
  { name: 'Venezia FC', logo: 'https://img.a.transfermarkt.technology/wappen/homepageWappen150x150/607.png?lm=4711', tc: 'ITA' },

  // Spain (ESP)
  { name: 'Athletic Bilbao', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/156.png', tc: 'ESP' },
  { name: 'Atlético Madrid', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/162.png', tc: 'ESP' },
  { name: 'CA Osasuna', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/306.png', tc: 'ESP' },
  { name: 'Celta de Vigo', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/355.png', tc: 'ESP' },
  { name: 'Deportivo Alavés', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/327.png', tc: 'ESP' },
  { name: 'Deportivo La Coruña', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/469.png', tc: 'ESP' },
  { name: 'Elche CF', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/538.png', tc: 'ESP' },
  { name: 'FC Barcelona', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/597.png', tc: 'ESP' },
  { name: 'Getafe CF', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/46/Getafe_logo.svg/960px-Getafe_logo.svg.png?utm_source=en.wikipedia.org&utm_campaign=imageinfo&utm_content=thumbnail', tc: 'ESP' },
  { name: 'Levante UD', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1207.png', tc: 'ESP' },
  { name: 'Málaga CF', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1262.png', tc: 'ESP' },
  { name: 'Racing Santander', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1517.png', tc: 'ESP' },
  { name: 'Rayo Vallecano', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1535.png', tc: 'ESP' },
  { name: 'RCD Espanyol', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/560.png', tc: 'ESP' },
  { name: 'Real Betis', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1543.png', tc: 'ESP' },
  { name: 'Real Madrid CF', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1545.png', tc: 'ESP' },
  { name: 'Real Sociedad', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1550.png', tc: 'ESP' },
  { name: 'Sevilla FC', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/1681.png', tc: 'ESP' },
  { name: 'Valencia CF', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/2041.png', tc: 'ESP' },
  { name: 'Villarreal CF', logo: 'https://s.hs-data.com/gfx/emblem/common/80x80/2102.png', tc: 'ESP' },
];